import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { Avatar, Grid, Typography } from "@mui/material";
import Image from "next/image";
import Myprofile from "../public/profile.jpg";
import Button from "@mui/material/Button";


const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NEXT JS APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <Grid container mt={2} display={"flex"}>
        <Grid item xs={12} md={6} lg={6}>
          <Typography variant="h5"></Typography>
          <Avatar sx={{ height: "200px", width: "200px", objectFit: "cover" }}>
            <Image src={Myprofile} width={200} height={200} alt="G" />
          </Avatar>
        </Grid>
        <Grid item xs={12} md={6} lg={6} textAlign={"justify"} mb={2}>
          <Typography variant="h4" mb={1}>
            Welcome to my portfolio
          </Typography>
          <Typography variant="subtitle1" mb={1}>
            👨‍💻 Professional Software Engineer | 💻 Frontend Developer |
            JavaScript | React/Next JS | TypeScript | React Native | 📝 Tech
            Posts Writer
          </Typography>
          <br />
          <Typography variant="body1">
            I am working as a software Developer from india. I am a ReactJS
            developer with FrontEnd Technologies. specializing in JS,ReactJS,
            TypeScript,Next js.
          </Typography>
        </Grid>
      </Grid>
      <Grid
        sx={{
          display: "flex",
          justifyContent: "space-evenly",
          alignItems: "center",
        }}
      >
        <Link href="/photos" passHref>
          <Button variant="contained">photos list</Button>
        </Link>
        <Link href="/eproduct" passHref>
          <Button variant="contained">go to e commerce page</Button>
        </Link>
        <Link href="/news" passHref>
          <Button variant="contained">go to news page</Button>
        </Link>
      </Grid>
    </div>
  );
};

export default Home;
